import os

# DOCKER ENVIRONMENT VARIABLES
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_ADMIN = os.environ.get("TELEGRAM_ADMIN")
TELEGRAM_GROUP = os.environ.get("TELEGRAM_GROUP")
TELEGRAM_THREAD = os.environ.get("TELEGRAM_THREAD")
IP_RANGE = os.environ.get("IP_RANGE")
LANGUAGE = os.environ.get("LANGUAGE")
HOURS_BETWEEN_SCANS = int(os.environ.get("HOURS_BETWEEN_SCANS"))

ANONYMOUS_USER_ID = "1087968824"
DATA_PATH = "/app/data"
KNOWN_DEVICES_FILE = "known_devices.json"
FULL_KNOWN_DEVICES_PATH = f'{DATA_PATH}/{KNOWN_DEVICES_FILE}'